global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.dockerswarm_cadvisormonitoring'
      type: 'A'
      port: 8080

  - job_name: 'node'
    dns_sd_configs:
    - names:
      - 'tasks.dockerswarm_node-exporter'
      type: 'A'
      port: 9100
