  version: "3"
  services:

    loadgenerator:
      container_name: loadgenerator
      image: locustio/locust
      ports: 
        - "5557:5557"
        - "8089:8089"
      volumes: 
        - ".:/mnt/locust"
      command: -f "/mnt/locust/locustfile.py"